### Recuperar todas las películas
GET http://localhost:3000/movies

### Recuperar una película por id
GET http://localhost:3000/movies/C6624C6C-5361-11EF-BD8B-E4A8DFAD8891


### Recuperar todas las películas por un género
GET http://localhost:3000/movies?genre=AcTioN

### Crear una película con POST
POST http://localhost:3000/movies
Content-Type: application/json

 {
    "id": "c906673b-3948-4402-ac7f-73ac3a9e3105",
    "title": "The Matrix",
    "year": 1999,
    "director": "Lana Wachowski",
    "duration": 136,
    "poster": "https://i.ebayimg.com/images/g/QFQAAOSwAQpfjaA6/s-l1200.jpg",
    "genre": ["Action", "Sci-Fi"],
    "rate": 8.7
  }

### Actualizar una película
PATCH http://localhost:3000/movies/DE58FD63-59AE-11EF-8F03-E4A8DFAD8891
Content-Type: application/json

{
  "sql":"SELECT * FROM prueba",
  "year": 1983,
  "title": "matrix",
  "director":"albeiro"
}
###eliminar

DELETE http://localhost:3000/movies/DE58FD63-59AE-11EF-8F03-E4A8DFAD8891

